version: '3.6'


services:
  project_name_docs:
    container_name: project_name_docs
    image: project_name_docs:latest
    build:
      context: ..
      dockerfile: ./docsify/Dockerfile
    ports:
      - 6007:80
    restart: unless-stopped
