---

services:
  project-name-raw-docs:
    container_name: project-name-raw-docs
    image: project-name-raw-docs:latest
    build:
      context: ..
      dockerfile: ./docsify/Dockerfile
    ports:
    - 3000:80
    restart: unless-stopped
