---
version: '3.6'

services:
  project_name_raw_docs:
    container_name: project_name_raw_docs
    image: project_name_raw_docs:latest
    build:
      context: ..
      dockerfile: ./docsify/Dockerfile
    ports:
    - 6007:80
    restart: unless-stopped
