FROM nginx:alpine

COPY ./docs /usr/share/nginx/html/docs
COPY ./docsify/index.html /usr/share/nginx/html/index.html
COPY ./icon.png /usr/share/nginx/html/icon.png
COPY ./CHANGELOG.md /usr/share/nginx/html/CHANGELOG.md
COPY ./CONTRIBUTING.md /usr/share/nginx/html/CONTRIBUTING.md
COPY ./LICENCE.md /usr/share/nginx/html/LICENCE.md
COPY ./README.md /usr/share/nginx/html/README.md
